name: "Check code-format workflow and manage comment"

on:
  workflow_run:
    # 监听 code-format.yml workflow 执行完成事件
    workflows: ["compare-binary-size"]
    types: [completed]

jobs:
  remove-comment-if-success:
    # 若 code-format 检查通过则移除之前发布的失败提示
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Remove existing "format check failed" comment
        uses: actions/github-script@v5
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const commitSha = context.payload.workflow_run.head_sha;

            // 获取触发 workflow_run 的 pull requests
            const { data: pullRequests } = await github.pulls.list({
              owner,
              repo,
              state: 'open',
              head: `${owner}:${context.payload.workflow_run.head_branch}`,
            });

            if (!pullRequests || pullRequests.length === 0) {
              console.log("No matching pull request found.");
              return;
            }

            // 假设只会找到一个对应的PR
            const pr = pullRequests.find(item => item.head.sha === commitSha);
            if (!pr) {
              console.log("No matching pull request found for the given SHA.");
              return;
            }

            // 获取该PR下所有comments
            const { data: comments } = await github.issues.listComments({
              owner,
              repo,
              issue_number: pr.number,
            });

            const targetComment = comments.find(comment =>
              comment.body.includes("code-format 检查失败，请修复后再提交。")
            );

            if (targetComment) {
              await github.issues.deleteComment({
                owner,
                repo,
                comment_id: targetComment.id,
              });
              console.log("Removed existing code-format failure comment.");
            } else {
              console.log("No existing format failure comment to remove.");
            }

  post-comment-if-failure:
    # 若 code-format 检查失败则创建新的失败提示，前提是当前 PR 中还没有此提示
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Post comment on failed code-format if not existing
        uses: actions/github-script@v5
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const commitSha = context.payload.workflow_run.head_sha;

            // 获取触发 workflow_run 的 pull requests
            const { data: pullRequests } = await github.pulls.list({
              owner,
              repo,
              state: 'open',
              head: `${owner}:${context.payload.workflow_run.head_branch}`,
            });

            if (!pullRequests || pullRequests.length === 0) {
              console.log("No matching pull request found.");
              return;
            }

            // 假设只会找到一个对应的PR
            const pr = pullRequests.find(item => item.head.sha === commitSha);
            if (!pr) {
              console.log("No matching pull request found for the given SHA.");
              return;
            }

            // 获取该PR下所有comments
            const { data: comments } = await github.issues.listComments({
              owner,
              repo,
              issue_number: pr.number,
            });

            // 如果已经有相关提示，就不再发布
            const existingComment = comments.find(comment =>
              comment.body.includes("code-format 检查失败，请修复后再提交。")
            );

            if (existingComment) {
              console.log("A code-format failure comment already exists.");
            } else {
              await github.issues.createComment({
                owner,
                repo,
                issue_number: pr.number,
                body: "code-format 检查失败，请修复后再提交。",
              });
              console.log("Created code-format failure comment.");
            }
