name: compare-binary-size
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]

jobs:
  compare-size:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          sudo apt-get update
          sudo apt-get install g++-arm-linux-gnueabihf g++-aarch64-linux-gnu
