name: compare-binary-size
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]

jobs:
  compare-size:
    runs-on: ubuntu-latest
    steps:
      - name: checkout pr branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          submodules: true
          path: pr

      - name: checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          repository: ${{ github.event.pull_request.base.repo.full_name }}
          submodules: true
          path: base

      - name: Compare sizes
        run: |
          # Define target architectures
          archs=("x86_64" "aarch64")

          for arch in "${archs[@]}"; do

            mkdir -p pr/build_$arch
            pushd pr/build_$arch
            cmake ..
            cmake --build . -j 4
            PR_SIZE_$arch=$(stat -c%s "hello")
            popd

            mkdir -p base/build_$arch
            pushd base/build_$arch
            cmake ..
            cmake --build . -j 4
            BASE_SIZE_$arch=$(stat -c%s "hello")
            popd

          done

          # Print table header
          echo "| Architecture | Base Size (bytes) | PR Size (bytes) | Difference (bytes) |"
          echo "|--------------|--------------------|-----------------|--------------------|"

          for arch in "${archs[@]}"; do
            DIFF=$((${PR_SIZE_$arch} - ${BASE_SIZE_$arch}))
            if [ $DIFF -gt 0 ]; then
              DIFF_STR="+$DIFF"
            else
              DIFF_STR="$DIFF"
            fi

            echo "| $arch | ${BASE_SIZE_$arch} | ${PR_SIZE_$arch} | $DIFF_STR |"
          done
